//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlotaVehiculos2._0b.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlotaVehiculosEntities : DbContext
    {
        public FlotaVehiculosEntities()
            : base("name=FlotaVehiculosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepCarga> DepCarga { get; set; }
        public virtual DbSet<DepTransporte> DepTransporte { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
    }
}
